######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 12 00:59:26 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ColorWheel.h
SOURCES += ColorWheel.cpp main.cpp
