######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 18 13:11:42 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BaseColorWheel.h ColorSlider.h HSLColorWheel.h
SOURCES += BaseColorWheel.cpp ColorSlider.cpp HSLColorWheel.cpp main.cpp
