######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 12 10:54:31 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BaseColorWheel.h HSLColorWheel.h
SOURCES += BaseColorWheel.cpp HSLColorWheel.cpp main.cpp
